# **Linear Regression using Scikit learn**

In [ ]:
import numpy as np
import pandas as pd

In [ ]:
df = pd.read_csv('/train(1).csv')
with pd.option_context('display.max_rows', None, 'display.max_columns', None):
  display(df)
df.shape
df.info()

,OverallQual,YearBuilt,YearRemodAdd,TotalBsmtSF,1stFlrSF,GrLivArea,FullBath,TotRmsAbvGrd,GarageCars,GarageArea,SalePrice,ExterQual_TA,Foundation_PConc,KitchenQual_TA
0,6,1969,1969,663,663,1352,1,7,1,299,158000,1,0,1
1,6,1920,1950,1012,1012,1012,1,6,1,308,118400,1,0,1
2,5,1910,2006,1022,1022,1022,1,4,1,280,85000,1,0,1
3,5,1973,1973,1656,1656,1656,2,8,2,506,135000,1,0,1
4,6,1978,1978,918,918,1683,2,7,2,440,172500,1,0,1
5,6,1957,2004,1477,1839,1839,2,7,2,416,257500,1,1,0
6,6,1915,1950,806,841,1647,1,6,1,216,128000,1,1,0
7,7,2005,2005,600,520,1223,2,4,2,480,147400,0,1,0
8,7,1968,1992,570,1222,1920,3,8,2,487,170000,1,0,0
9,5,1963,1963,1120,1128,1128,2,6,2,525,155000,1,0,1
10,6,1931,1950,884,959,1367,1,6,1,560,127500,1,0,1
11,7,1970,1970,1304,1682,1682,2,7,2,530,174000,1,1,1
12,8,1932,1994,853,1549,2727,2,10,2,440,315000,0,0,0
13,10,1994,1995,2444,2444,4316,3,10,3,832,755000,0,1,0
14,5,1972,2007,768,768,768,1,5,2,396,133000,1,0,1
15,9,2005,2006,1175,1182,2324,3,11,3,736,345000,0,1,0
16,7,1989,1989,807,1175,1982,2,7,2,575,228500,0,0,0
17,8,2006,2006,1088,1088,1959,2,8,3,1025,270000,0,1,0
18,6,1993,1994,799,799,1571,2,7,2,380,178000,0,1,1
19,7,2006,2006,728,728,1456,2,8,2,440,155835,0,1,0
20,4,1927,1950,520,520,520,1,4,1,240,68500,1,0,0
21,5,1968,1968,1052,1052,1052,1,5,1,288,138500,1,0,1
22,7,2003,2003,941,941,1829,2,7,2,613,237000,0,1,0
23,7,2005,2006,1373,1555,1555,2,7,2,430,192500,0,1,0
24,6,1937,1950,780,780,1375,1,6,1,544,141000,1,1,0
25,7,2003,2003,783,807,1509,2,8,2,393,180000,0,1,0
26,6,1968,1968,708,708,1416,2,7,2,776,179900,1,0,1
27,6,2000,2000,936,962,1792,2,8,2,451,186500,1,1,1
28,7,1996,1996,880,909,1716,2,7,2,512,191000,0,1,0
29,5,1920,1996,530,581,1111,1,6,1,288,101000,1,0,0
30,5,1940,1997,672,672,672,1,4,1,240,108000,1,1,1
31,6,1970,1970,483,483,987,1,5,1,280,106000,1,0,1
32,5,1966,1966,894,894,894,1,5,1,384,125000,1,0,1
33,6,1997,1998,1478,1493,1493,2,7,2,508,208900,1,1,0
34,7,2007,2007,728,728,1456,2,8,2,400,179540,0,1,0
35,4,1954,2000,901,901,901,1,4,1,281,107900,1,0,1
36,5,1977,2008,1040,1040,1040,2,5,2,484,150500,1,0,0
37,6,1984,2003,585,1140,1868,3,7,2,477,178000,1,0,1
38,10,2007,2008,2078,2084,2084,2,7,3,1220,385000,0,1,0
39,9,1999,1999,1393,1422,2599,2,10,3,779,333168,0,1,0
40,6,1985,1985,741,977,1732,2,7,2,476,178000,0,0,0
41,6,1940,2000,940,1192,1595,1,6,1,240,140000,1,0,1
42,6,1977,1977,975,1004,1004,1,4,2,504,135000,1,0,1
43,4,1945,1950,747,747,747,1,4,1,220,80000,1,0,1
44,5,1969,1969,1040,1040,2080,1,9,2,504,135000,1,1,0
45,6,1954,1972,994,1216,1855,2,7,1,325,136900,1,0,1
46,6,1994,1998,1408,1679,1679,2,7,2,575,193500,1,1,0
47,6,1930,2005,813,813,813,1,5,1,270,110000,1,0,0
48,5,1959,2002,1063,1327,1327,1,7,2,624,150750,1,0,0
49,6,1960,1960,1080,1656,1656,1,7,2,528,215000,1,0,1
50,6,1988,1988,1392,1412,1412,2,6,2,576,175000,1,0,0
51,5,1952,1952,540,1044,1044,1,4,2,504,55993,0,0,0
52,6,1973,1973,942,1291,2521,2,10,2,576,151400,1,0,1
53,8,1994,1995,1463,1500,2622,2,9,2,712,325000,0,1,0
54,8,1995,1995,2109,2113,2113,2,7,3,839,350000,0,1,0
55,5,1959,1959,1150,1150,1150,1,6,1,300,141000,1,0,1
56,10,2009,2009,2006,2020,2020,2,9,3,900,402861,0,0,0
57,6,1998,1998,1204,1204,1204,2,5,2,412,162000,1,1,1
58,6,1928,1950,896,1172,1913,1,9,2,342,177000,1,0,1
59,5,1961,1961,1235,1235,1235,1,6,2,480,98600,1,0,1
60,4,1957,1957,907,907,907,1,5,1,352,109008,1,0,1
61,3,1915,1950,840,840,1605,2,8,1,379,107400,0,0,1
62,5,1972,1972,882,882,882,1,5,2,461,112500,1,0,1
63,6,1958,1958,1442,1442,1442,1,7,1,301,157900,1,0,1
64,4,1910,2000,560,796,1346,1,6,1,384,112000,1,0,1
65,8,2004,2004,1136,1136,2468,2,10,3,872,354000,0,1,0
66,7,1941,1950,918,918,1646,2,7,1,240,164000,1,0,1
67,5,1940,1955,740,778,778,1,4,1,924,120500,1,0,1
68,4,1939,1950,732,772,1123,1,4,1,264,100000,1,1,1
69,8,1934,1998,965,1940,3194,2,10,2,380,359100,1,1,1
70,7,1999,1999,744,757,1501,2,6,2,440,179400,1,1,1
71,4,1937,2000,907,1131,1131,1,7,2,672,89471,1,0,1
72,5,1930,1950,912,912,1248,1,6,1,160,87000,1,0,1
73,7,2004,2004,970,970,1709,2,7,2,380,137500,0,1,0
74,7,1997,1998,975,975,1950,2,7,2,576,239000,0,1,0
75,6,1977,1977,1069,1069,1069,2,4,2,440,127500,1,0,1
76,6,1918,2000,816,838,838,1,5,1,275,130000,1,0,0
77,7,2006,2006,939,939,1797,2,8,2,639,213500,0,1,0
78,7,1999,2000,600,624,1252,2,4,2,462,160000,0,1,0
79,5,1959,1959,1040,1040,1040,1,6,1,286,133700,1,0,1
80,4,1928,1950,1122,1328,1981,2,7,2,576,135000,1,0,0
81,5,1936,1989,796,1096,1466,2,7,2,566,170000,1,0,0
82,7,1996,1997,1379,1383,2398,2,8,3,834,315750,0,1,0
83,5,1958,1958,874,874,1524,1,7,1,315,144000,1,0,1
84,7,2002,2003,817,824,1894,2,8,2,510,214900,0,1,0
85,8,2007,2008,1580,1580,1580,2,7,3,830,235128,0,1,0
86,8,2008,2008,768,786,1590,2,6,2,676,210000,0,1,0
87,6,1941,1950,806,958,1578,1,5,1,240,133000,1,0,0
88,5,1913,2002,440,694,694,1,4,1,352,90350,1,1,0
89,5,1950,1996,1078,1078,1078,1,5,1,240,142125,1,0,0
90,5,1947,1950,832,832,1216,1,6,1,336,118500,1,0,1
91,7,1920,1988,650,832,1482,1,7,2,324,143000,1,1,1
92,6,1998,1998,943,943,1638,2,7,2,472,192000,1,1,1
93,8,1992,1992,908,927,1915,2,8,2,506,220000,0,1,0
94,5,1900,1950,861,961,1367,1,7,1,384,119000,1,0,1
95,5,1945,1950,913,1048,1558,1,6,1,288,140000,1,0,1
96,7,2003,2004,847,847,1928,2,8,2,434,219500,0,1,0
97,9,2008,2009,1734,1734,2822,3,12,3,1020,582933,0,1,0
98,8,2007,2007,1466,1466,1466,2,7,3,610,201000,0,1,0
99,7,1998,1998,935,955,1632,2,8,2,462,176500,1,1,1
100,10,1995,1996,1930,1831,3627,3,10,3,807,625000,0,1,0
101,5,1954,1954,936,1128,1128,1,5,1,286,118000,1,0,1
102,5,1958,1987,533,1021,1601,1,6,1,300,140000,1,0,1
103,5,1968,1968,894,894,894,1,5,2,450,129000,1,0,1
104,9,1981,1987,1842,1842,1842,0,5,3,894,385000,0,0,0
105,7,1998,1998,1649,1661,1661,2,6,2,598,224900,1,1,0
106,5,1925,1950,768,1015,1015,1,6,1,450,88000,1,0,1
107,8,1882,1986,916,916,1742,1,8,2,424,168000,0,0,0
108,6,1966,2002,1517,1888,1888,2,6,2,578,190000,0,0,0
109,7,2006,2007,1352,1352,1352,2,5,2,466,208900,0,1,0
110,6,1986,1986,1606,1651,1651,2,7,2,616,184000,1,0,1
111,7,2007,2007,1386,1569,1569,2,7,3,660,175900,0,1,0
112,8,2008,2009,1468,1468,1468,2,6,3,898,244600,0,1,0
113,6,1948,1950,1082,1082,1082,1,5,1,240,119200,1,0,1
114,4,1950,1995,1067,1067,1067,2,4,2,436,128000,1,0,0
115,7,1978,1978,1392,1392,2784,3,12,2,564,250000,1,0,0
116,7,1999,1999,873,882,1790,2,7,2,588,193000,0,1,0
117,5,1920,1950,596,596,1192,1,6,1,189,78000,1,1,1
118,4,1935,1995,884,989,1573,1,6,1,240,133000,1,0,0
119,6,1946,1950,979,979,1958,2,8,2,492,145000,1,0,1
120,9,2004,2005,1833,1850,1850,2,8,3,772,326000,0,1,0
121,6,1994,1994,928,936,1721,2,7,2,471,201000,0,1,0
122,7,2005,2006,1368,1368,1368,2,6,2,474,202500,0,1,0
123,4,1951,1951,836,1220,1220,1,6,2,396,102000,1,0,1
124,9,2005,2006,1992,1992,2868,3,11,3,716,556581,0,1,0
125,7,2007,2008,1314,1314,1314,2,6,2,626,230000,0,1,0
126,4,1920,1950,840,840,1374,1,6,1,338,105000,0,1,1
127,4,1920,1950,637,897,1336,1,7,1,570,108000,1,0,1
128,5,1950,2002,864,864,864,1,5,2,720,129000,1,0,0
129,5,1966,1966,1024,1086,1086,1,6,2,484,159950,1,0,1
130,8,2006,2006,1623,1636,1636,2,8,3,865,255000,0,1,0
131,6,1935,1986,1127,1236,2108,2,7,2,540,235000,1,0,0
132,7,2001,2001,963,963,1792,2,7,2,564,231500,0,1,0
133,8,2006,2006,1079,1079,1919,2,8,2,685,233230,0,1,0
134,7,2005,2006,1392,1392,2462,2,9,2,576,320000,0,1,0
135,5,1958,1992,1056,1056,1056,1,6,1,308,139000,1,0,1
136,6,2003,2004,1114,1114,1114,1,6,2,576,155000,1,1,0
137,5,1948,2005,924,1122,1122,1,6,2,528,147000,1,0,0
138,6,1984,1984,1003,1003,1003,1,6,2,588,142500,1,0,1
139,8,1991,1992,1288,1301,2417,2,9,2,462,260000,0,0,0
140,8,2008,2008,1694,1694,1694,2,7,3,776,245350,0,1,0
141,8,2009,2010,774,774,1968,2,8,3,680,269500,0,1,0
142,7,1936,2007,560,575,1135,1,6,2,576,155000,0,1,0
143,5,1963,1963,1040,1040,1040,1,5,1,308,133000,1,0,1
144,5,1930,1960,742,779,935,1,4,1,308,79500,1,0,1
145,5,1960,2002,1010,1134,1134,1,6,1,254,135000,1,0,1
146,9,2005,2006,1848,1848,2728,2,10,3,706,437154,0,1,0
147,5,1947,1950,720,720,1284,1,5,1,240,110000,1,0,1
148,6,1957,1996,912,1236,1236,1,6,2,923,149700,1,0,1
149,6,1997,1997,1479,1494,1494,2,6,2,576,217000,1,1,0
150,7,1987,1987,1064,1064,1767,2,5,2,504,239000,0,1,0
151,8,2002,2002,967,993,1908,2,9,2,431,202900,0,1,0
152,6,1968,1968,1392,1392,1392,1,5,2,576,110000,1,0,1
153,6,1965,1965,1088,1324,1324,2,6,2,440,160000,1,0,1
154,6,2003,2003,848,848,848,1,3,2,420,131500,0,1,0
155,7,2003,2003,764,764,1626,2,6,2,474,175500,0,1,0
156,9,2003,2004,1896,1944,1944,2,8,3,708,360000,0,1,0
157,7,2009,2009,846,846,1692,2,6,2,650,224500,1,1,0
158,9,2006,2006,1838,1838,1838,2,8,3,765,315000,0,1,0
159,5,1960,1960,1269,1269,1269,1,6,1,308,155000,1,0,1
160,5,1958,1991,1008,1053,1053,1,6,2,750,150000,1,0,0
161,8,1970,1970,2217,2217,2217,2,8,2,621,268000,0,1,0
162,6,1962,1962,858,858,1716,1,8,2,490,171000,1,0,1
163,5,1954,2000,833,833,833,1,4,1,326,117000,1,0,0
164,5,1977,1977,1430,1647,1647,2,7,2,621,217500,1,0,0
165,6,1939,1950,780,825,1412,1,6,1,280,132500,1,0,1
166,8,1994,1995,1624,1624,1624,2,5,3,757,262000,0,1,0
167,6,1973,1973,483,483,987,1,5,1,264,100000,1,0,1
168,6,2009,2009,1218,1218,1218,2,4,2,676,208300,0,1,0
169,8,2004,2005,1713,1713,1713,2,7,3,856,274900,0,1,0
170,4,1938,1958,816,816,816,1,3,1,288,100000,1,0,1
171,7,1990,1990,1673,1699,3222,3,11,3,594,320000,1,1,0
172,6,1910,1950,1020,908,1928,2,9,1,440,137000,1,0,0
173,7,1996,1997,1306,1306,2260,2,7,2,533,328000,0,1,0
174,7,1915,2005,910,916,1826,1,7,1,164,155000,0,1,0
175,7,1999,1999,1490,1501,1501,2,6,2,577,204000,0,1,0
176,3,1935,1950,894,894,894,1,6,3,1248,81000,0,0,1
177,10,2007,2008,3138,3138,4676,3,11,3,884,184750,0,1,0
178,5,1958,1958,1276,1276,1276,1,5,1,350,60000,1,0,1
179,8,2004,2005,1594,1646,1646,2,5,2,482,275000,0,1,0
180,6,1968,1968,727,829,1556,1,8,2,441,154000,1,0,1
181,8,2007,2008,1638,1646,1646,2,7,3,800,293077,0,1,0
182,7,2006,2007,625,625,1250,2,5,2,625,171900,0,1,0
183,6,1910,2003,485,1001,1635,1,5,1,255,117000,1,0,0
184,8,1994,2005,1629,1686,2448,2,8,3,711,402000,0,1,0
185,7,2000,2000,384,774,1430,2,8,2,400,170000,1,1,1
186,7,2005,2005,1257,1266,1266,2,6,2,453,176000,0,1,0
187,7,1998,1998,832,885,1718,2,7,2,427,185000,1,1,1
188,6,1977,1977,1844,1844,1844,2,7,2,546,190000,1,0,1
189,5,1946,1995,768,768,1200,1,6,1,240,130500,1,0,1
190,4,1970,1970,546,546,1092,1,6,1,286,88000,1,0,1
191,6,1919,1990,804,1699,2447,2,10,1,336,169000,1,1,0
192,8,2006,2006,1709,1717,1717,2,7,3,908,255500,0,1,0
193,2,1920,1950,290,438,438,1,3,1,246,60000,1,0,0
194,9,2005,2005,1561,1561,1561,2,6,2,556,277500,0,1,0
195,10,2008,2008,6110,4692,5642,2,12,2,1418,160000,0,1,0
196,7,2007,2007,1208,1208,1208,2,6,2,628,195400,0,1,0
197,5,1961,1961,1144,1144,1144,1,6,2,456,139950,1,0,1
198,5,1918,1950,686,686,1250,1,7,1,280,116000,1,0,0
199,5,1948,1950,810,1002,1456,1,7,1,280,91500,1,0,1
200,6,1964,1964,780,798,1611,1,7,2,442,167900,1,0,1
201,5,1975,1975,924,924,924,1,5,1,280,110000,1,0,1
202,7,2003,2003,798,798,1640,2,6,2,595,183000,0,1,0
203,4,1936,1950,672,757,1324,1,6,1,240,128000,1,0,1
204,5,1920,1997,672,672,1344,1,6,1,468,147000,1,0,1
205,7,2007,2007,1726,1726,1726,2,8,3,786,311872,0,1,0
206,9,1999,2000,1698,1709,1709,2,5,2,506,328900,0,1,0
207,7,1994,1994,1223,1223,2127,2,5,2,525,271000,0,1,0
208,7,2004,2004,1358,1358,1358,2,6,2,484,207000,0,1,0
209,5,1963,1963,970,970,970,1,5,2,624,132500,1,0,1
210,7,2007,2007,874,874,1761,3,7,2,578,227875,0,1,0
211,5,1957,1957,928,928,928,1,5,1,288,112500,1,0,1
212,8,2002,2002,1800,1800,1800,2,7,3,765,312500,0,1,0
213,5,1967,1967,1632,1632,1632,2,8,2,576,143000,1,0,1
214,6,1971,1971,483,483,987,1,5,1,264,89500,1,0,1
215,8,2006,2007,1732,1776,1776,2,7,3,712,283463,0,1,0
216,8,2007,2007,1566,1600,1600,2,7,3,890,256300,0,1,0
217,8,1972,1995,1952,2000,2704,2,9,2,538,345000,0,0,0
218,5,1962,1962,1140,1696,1696,1,8,1,349,143900,1,0,1
219,5,1968,1993,1461,1721,1721,2,7,2,440,180000,1,0,1
220,7,2003,2003,856,856,1710,2,8,2,548,208500,0,1,0
221,6,1926,2004,1149,1149,1616,2,5,1,216,152000,1,0,0
222,5,1924,1950,1145,1301,1301,1,5,2,440,100000,1,1,0
223,5,1982,1982,816,816,816,1,5,1,264,124500,1,0,1
224,8,2003,2003,1657,1668,1668,2,8,2,502,232000,0,1,0
225,7,2005,2007,1274,1274,1274,2,6,2,508,203000,0,1,0
226,7,2000,2001,1349,1349,1349,2,6,2,539,179000,1,1,1
227,7,1969,1969,1164,1164,1164,1,6,2,528,140000,1,0,1
228,6,2004,2004,839,864,1593,2,8,2,398,193000,1,1,1
229,5,1923,2004,1324,1072,1576,1,6,2,528,223500,1,0,0
230,5,1961,1994,912,1236,1236,1,6,1,288,135000,1,0,1
231,5,1995,1995,990,990,990,1,5,2,576,156000,1,1,1
232,5,1976,1976,1728,1728,1728,2,8,2,560,188000,1,0,1
233,5,1972,1972,864,864,864,1,5,1,352,127000,1,0,1
234,5,1953,1953,608,1319,1319,1,5,1,270,123000,1,1,1
235,5,1954,2005,1056,1056,1056,1,6,1,260,139400,1,0,1
236,6,1973,1973,672,672,1218,1,7,1,264,113000,1,0,1
237,6,1954,1954,832,832,832,1,4,2,528,105500,1,0,0
238,7,2003,2003,1453,1479,1479,2,7,2,558,226000,0,1,0
239,8,1997,1998,1396,1407,2392,2,7,3,870,348000,0,1,0
240,5,1954,1954,1050,1050,1795,2,7,1,352,131500,1,0,1
241,5,1948,2001,672,1072,1285,1,6,1,240,127000,1,0,1
242,6,1934,1950,816,816,1176,1,6,2,528,114500,1,1,1
243,8,1998,1999,1225,1276,2612,2,8,3,676,336000,0,1,0
244,8,1994,1994,1165,1203,2526,2,8,3,844,290000,0,1,0
245,9,2002,2002,1626,1668,1668,2,7,3,702,285000,0,1,0
246,4,1970,2002,630,630,630,1,3,1,286,86000,1,0,0
247,6,1920,1950,648,734,1118,1,6,2,440,116000,1,0,1
248,7,2004,2004,1422,1422,1422,2,7,2,626,179600,0,1,0
249,10,2008,2008,1017,1026,2007,2,10,3,812,310000,0,1,0
250,5,1974,1975,1389,1389,1389,1,6,2,418,170000,1,0,1
251,4,1970,1970,630,630,630,1,3,1,286,80000,1,0,1
252,5,1954,1990,1297,1297,1297,1,5,2,498,153000,1,0,1
253,6,1964,1964,1251,1251,1251,1,6,1,461,160000,1,0,1
254,6,1984,1984,744,752,752,1,4,1,264,125000,1,0,1
255,7,2006,2006,1286,1294,1294,2,6,2,662,193879,0,1,0
256,7,2003,2003,840,840,1668,2,8,2,500,180000,0,1,0
257,4,1900,1950,859,859,1178,1,7,1,384,102776,1,0,1
258,7,2003,2003,1434,1518,2149,1,6,2,670,239686,0,1,0
259,5,1953,2006,1008,1008,1008,1,6,1,240,134500,1,0,0
260,6,1964,1964,1516,1516,1516,1,6,2,472,167000,1,0,1
261,8,1988,1989,1228,1228,1228,2,5,2,472,189000,0,1,0
262,6,1988,1989,1461,1509,1509,2,5,2,600,175000,0,0,0
263,8,2004,2005,1143,1143,2473,2,9,3,852,317000,0,1,0
264,7,1996,1996,1720,1720,1720,2,7,2,527,260400,0,1,0
265,9,2006,2007,1652,1652,1652,2,6,2,840,325000,0,1,0
266,8,2003,2004,1518,1518,1518,1,6,2,588,274000,0,1,0
267,5,1938,1950,920,954,954,1,5,1,240,119750,1,1,0
268,9,2006,2006,2153,2069,2643,2,9,3,694,380000,0,1,0
269,7,2009,2009,1226,1226,1226,2,6,3,740,198900,1,1,0
270,5,1949,2008,768,1148,1716,1,8,1,281,131000,1,0,1
271,6,1992,1992,761,810,1603,2,7,2,484,175900,0,1,0
272,8,1995,1996,1595,1616,1616,2,5,2,608,236500,0,1,0
273,5,1956,2000,928,928,928,1,4,1,252,132000,1,0,1
274,6,1910,1998,1214,1260,2291,2,9,2,506,133900,1,0,1
275,4,1963,1979,1051,1382,1382,1,6,2,459,148000,1,0,1
276,6,1958,1988,1240,1632,1632,2,6,1,338,139000,1,0,1
277,8,2006,2007,1638,1646,1646,2,6,3,870,248900,0,1,0
278,8,2006,2007,1573,1625,1625,2,5,2,538,235000,0,1,0
279,8,2005,2006,1844,1844,1844,2,7,2,620,257000,0,1,0
280,5,1948,2002,896,1112,2008,3,8,1,230,225000,1,0,0
281,7,2000,2001,1630,1630,1630,2,6,2,451,213000,0,1,0
282,6,1980,1980,626,626,1217,1,6,1,288,120000,1,0,1
283,8,2005,2006,1158,1158,2376,3,9,3,853,325300,0,1,0
284,6,1937,1950,780,780,1376,2,7,1,198,119500,1,0,1
285,5,1966,1966,955,955,955,1,6,1,386,127000,1,0,1
286,5,1948,1950,789,789,789,1,5,1,250,115000,1,0,1
287,7,2004,2005,1860,1836,1836,2,8,2,484,216837,0,1,0
288,5,1969,1969,780,780,1620,2,7,2,462,152000,1,0,1
289,5,1954,2003,1086,1086,1086,1,6,2,490,144900,1,0,1
290,7,2006,2007,1092,1112,1550,2,7,2,438,241000,0,1,0
291,6,1925,1950,672,697,1369,2,6,1,300,103600,1,0,1
292,5,1976,1976,894,894,894,1,5,1,308,128200,1,0,1
293,6,1968,1968,702,1041,1743,1,7,2,539,175000,0,0,1
294,8,2004,2005,1580,1580,2466,3,8,2,610,340000,0,1,0
295,6,1988,1989,1151,1164,2060,2,8,2,521,211000,0,1,1
296,5,1967,1967,864,900,900,1,6,1,288,123000,1,0,1
297,7,2003,2003,1362,1362,2082,2,6,2,484,200000,1,1,0
298,5,1920,1950,458,835,835,1,5,1,366,83000,1,0,1
299,8,2000,2000,1501,1659,1659,2,5,2,499,278000,0,1,0
300,4,1925,1950,780,848,1208,1,5,2,539,103000,1,0,1
301,5,1965,1965,1040,1040,1040,1,5,1,384,129500,1,0,1
302,5,1952,1952,960,960,1960,2,10,2,400,124500,1,0,1
303,4,1970,1970,546,546,1092,1,6,1,286,75000,1,0,1
304,7,2001,2001,944,944,1840,2,6,2,622,230000,0,1,0
305,10,1996,1996,2396,2411,4476,3,10,3,813,745000,0,1,0
306,6,1928,2003,624,720,720,1,5,2,484,105900,1,0,1
307,8,1993,1994,777,1065,1911,2,8,2,471,215000,0,1,0
308,7,2006,2007,625,625,1250,2,5,2,528,164700,0,1,0
309,6,1937,2000,698,786,1176,1,4,2,624,134900,0,0,1
310,5,1964,1964,912,912,912,1,5,1,288,115000,1,0,1
311,3,1955,2005,1162,1163,1163,1,6,1,220,126175,1,0,1
312,5,1900,1996,360,1032,1812,2,8,2,672,140000,1,0,0
313,6,1929,1950,862,950,1158,1,5,1,208,120000,1,0,1
314,4,1970,1970,864,864,864,1,5,2,463,124500,1,0,1
315,5,1996,1996,1040,1040,1040,1,6,2,576,152000,1,1,0
316,5,1965,1998,864,1200,1200,1,6,2,884,146000,1,0,0
317,7,1976,1976,1090,1370,1370,2,6,2,479,152000,1,0,1
318,7,1931,2000,776,851,1502,1,6,1,270,149000,1,0,1
319,7,1999,1999,975,1005,2291,2,8,2,429,230000,0,1,0
320,8,1988,2005,559,1080,1752,2,8,2,492,164000,0,0,1
321,6,1957,1957,1244,1244,1244,1,6,1,336,150000,1,0,1
322,5,1921,1968,1073,1073,1073,1,4,1,326,108480,1,0,1
323,5,1957,1957,1092,1092,1092,1,6,1,299,141000,1,0,1
324,4,1951,1951,864,864,864,1,4,2,400,141000,1,0,1
325,5,1971,1971,1484,1484,1484,2,7,2,487,175000,1,0,1
326,5,1960,1960,1065,1065,1065,1,6,2,461,126500,1,0,1
327,5,1950,1982,1208,1136,1904,1,7,1,240,138000,1,0,1
328,6,1928,1950,784,784,784,1,5,2,360,76000,1,0,1
329,6,1975,1975,713,811,1552,2,6,2,434,179900,1,0,1
330,6,1956,1956,1436,1689,1689,1,7,2,480,127500,1,0,1
331,7,2004,2005,1710,1710,1710,2,7,2,550,240000,0,1,0
332,8,2004,2005,1117,1132,2452,3,9,3,691,309000,0,1,0
333,6,1974,1974,855,855,1322,2,6,2,440,147000,1,0,1
334,5,1959,2005,1626,1712,1712,2,8,2,588,145000,1,0,1
335,5,1900,1970,954,1766,2414,2,10,2,520,160000,1,0,1
336,7,1999,1999,994,1028,1804,2,7,2,442,189000,1,1,0
337,6,1945,1950,735,798,1487,1,7,1,220,113000,1,0,1
338,5,1938,1996,190,886,886,1,4,1,273,91300,1,0,1
339,8,2007,2007,1582,1610,2161,1,8,3,789,325624,0,1,0
340,6,1997,1997,824,905,1786,2,7,2,684,204750,1,1,0
341,6,1958,1958,588,1095,1095,1,6,1,264,140000,1,0,1
342,5,1961,1983,864,1144,1144,1,6,1,264,131400,1,0,1
343,5,1957,2000,992,1306,1306,1,5,1,756,153000,1,0,1
344,8,2005,2005,1030,1038,2098,2,8,3,878,275500,0,1,0
345,7,2004,2005,716,716,1432,2,6,2,432,188500,0,1,0
346,6,1926,1950,960,986,986,1,5,1,180,102000,1,0,1
347,5,1939,1997,720,1052,2192,2,8,1,240,179500,1,1,0
348,7,2004,2005,788,788,1490,2,8,2,388,184000,0,1,0
349,8,1992,2000,1683,2129,2872,2,9,2,541,285000,0,1,0
350,6,1950,2001,1202,2158,2158,2,7,2,576,243000,1,0,0
351,5,1954,1954,1056,1063,1063,1,6,1,280,128000,1,0,1
352,5,1960,1960,1105,1105,2274,2,12,2,480,154300,1,0,1
353,7,2003,2004,746,760,1656,2,7,2,397,165400,0,1,0
354,8,1993,1993,1719,1719,1719,1,6,2,473,324000,0,1,0
355,4,1970,1970,960,960,960,1,6,2,576,129000,1,0,1
356,7,1929,2001,832,854,854,1,5,2,576,132000,1,0,1
357,7,2008,2008,1417,1428,1428,2,6,2,554,227680,0,1,0
358,5,1963,1963,1728,1728,1728,2,10,2,504,125000,1,0,1
359,5,1956,2000,936,936,936,1,4,1,308,129000,1,0,1
360,5,1939,1950,991,1077,1077,1,5,1,205,118000,1,0,1
361,6,2006,2006,1262,1262,1262,2,5,2,572,185000,0,1,0
362,4,1971,1971,864,864,864,1,5,2,528,120500,1,1,1
363,5,1915,1950,876,876,1416,1,7,3,720,153900,1,0,1
364,8,2006,2006,1324,1324,1324,2,6,2,550,254000,0,1,0
365,8,2006,2006,1574,1574,1574,2,7,3,824,232000,0,1,0
366,6,1979,1998,1362,1586,1586,2,7,2,435,181000,1,0,1
367,7,2007,2008,1314,1314,1314,2,6,2,626,207500,0,1,0
368,5,1962,1962,1106,1190,1190,1,6,2,540,132500,1,0,1
369,9,2008,2008,1702,1702,1702,1,7,3,1052,367294,0,1,0
370,7,2004,2004,1530,1530,1530,2,7,3,630,259000,0,1,0
371,6,2005,2005,684,684,1560,2,6,2,400,174000,0,1,0
372,5,1976,1976,536,536,1112,1,4,1,336,85000,1,0,1
373,7,2006,2006,1199,1220,1220,2,6,2,632,194000,0,1,0
374,7,1968,1968,2110,2110,2110,2,8,2,522,244000,0,0,0
375,7,2004,2004,970,970,1709,2,7,2,380,130000,0,1,0

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 765 entries, 0 to 764
Data columns (total 14 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   OverallQual       765 non-null    int64
 1   YearBuilt         765 non-null    int64
 2   YearRemodAdd      765 non-null    int64
 3   TotalBsmtSF       765 non-null    int64
 4   1stFlrSF          765 non-null    int64
 5   GrLivArea         765 non-null    int64
 6   FullBath          765 non-null    int64
 7   TotRmsAbvGrd      765 non-null    int64
 8   GarageCars        765 non-null    int64
 9   GarageArea        765 non-null    int64
 10  SalePrice         765 non-null    int64
 11  ExterQual_TA      765 non-null    int64
 12  Foundation_PConc  765 non-null    int64
 13  KitchenQual_TA    765 non-null    int64
dtypes: int64(14)
memory usage: 83.8 KB

In [ ]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(df.drop('SalePrice',axis=1),df['SalePrice'],test_size=0.2,random_state=42)

In [ ]:
from sklearn.linear_model import LinearRegression
lr = LinearRegression()
lr.fit(X_train,y_train)
y_pred = lr.predict(X_test)

In [ ]:
from sklearn.metrics import r2_score
r2_score(y_test,y_pred)

0.80787885626767

In [ ]:
X_train.head()

,OverallQual,YearBuilt,YearRemodAdd,TotalBsmtSF,1stFlrSF,GrLivArea,FullBath,TotRmsAbvGrd,GarageCars,GarageArea,ExterQual_TA,Foundation_PConc,KitchenQual_TA
336,7,1999,1999,994,1028,1804,2,7,2,442,1,1,0
688,5,1957,2002,1216,1526,1526,1,7,1,364,1,0,1
290,7,2006,2007,1092,1112,1550,2,7,2,438,0,1,0
687,6,2003,2003,864,864,1728,2,7,2,673,0,1,0
90,5,1947,1950,832,832,1216,1,6,1,336,1,0,1

In [ ]:
X_test

,OverallQual,YearBuilt,YearRemodAdd,TotalBsmtSF,1stFlrSF,GrLivArea,FullBath,TotRmsAbvGrd,GarageCars,GarageArea,ExterQual_TA,Foundation_PConc,KitchenQual_TA
357,7,2008,2008,1417,1428,1428,2,6,2,554,0,1,0
259,5,1953,2006,1008,1008,1008,1,6,1,240,1,0,0
751,5,1957,2000,1134,1803,1803,2,8,2,484,1,0,1
193,2,1920,1950,290,438,438,1,3,1,246,1,0,0
333,6,1974,1974,855,855,1322,2,6,2,440,1,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...
60,4,1957,1957,907,907,907,1,5,1,352,1,0,1
552,7,1910,1950,925,964,1889,1,9,1,308,0,0,1
342,5,1961,1983,864,1144,1144,1,6,1,264,1,0,1
324,4,1951,1951,864,864,864,1,4,2,400,1,0,1
244,8,1994,1994,1165,1203,2526,2,8,3,844,0,1,0

# **Linear Regression using Numpy**

In [ ]:
X_train = df.drop('SalePrice',axis=1).to_numpy()
y_train = df['SalePrice'].to_numpy()
X_test = X_test.to_numpy()
y_test = y_test.to_numpy()

In [ ]:
class MyLinearRegression:
  def __init__(self):
    self.coef_ = None
    self.intercept_ = None
  def fit(self,X_train,y_train):
    X_train = np.insert(X_train,0,1,axis=1)
    beta = np.linalg.inv(np.dot(X_train.T,X_train)).dot(X_train.T).dot(y_train)
    self.coef_ = beta[1:]
    self.intercept_ = beta[0]
  def predict(self,X_test):
    return np.dot(X_test,self.coef_) + self.intercept_
  def score(self,y_test,y_pred):
    return r2_score(y_test,y_pred)

In [ ]:
reg = MyLinearRegression()
reg.fit(X_train,y_train)
y_pred = reg.predict(X_test)
reg.score(y_test,y_pred)

0.821764919942368

In [ ]:
X_train

array([[   6, 1969, 1969, ...,    1,    0,    1],
       [   6, 1920, 1950, ...,    1,    0,    1],
       [   5, 1910, 2006, ...,    1,    0,    1],
       ...,
       [   5, 1955, 1990, ...,    1,    0,    1],
       [   5, 1956, 1956, ...,    1,    0,    1],
       [   7, 2006, 2007, ...,    0,    1,    0]])